### ISSUE TITLE
Products are not displayed

### ISSUE THREAD

**Issue by Pranav50** [shamahoque/mern-marketplace#5]
I have connected to MongoDB but the products aren't fetched and displayed

**Comment by shamahoque** [comment]
Did you create the shop and products successfully from a retailer account? Are you seeing any errors in the console?

**Comment by Pranav50** [comment]
Thanks for the reply.... So we have to create the products? I assumed that
the products are fetched from json values... I will try again. Please help
me if I 'am stuck in the project, since I am new to React.js
