### ISSUE TITLE
compile failure in order.controller.js

### ISSUE THREAD

**Issue by zz245** [shamahoque/mern-marketplace#6]
I failed to compile with the following error:
ERROR in ./server/controllers/order.controller.js
Module not found: Error: Can't resolve '../models/Order.model' in '/home/admin/marketplace/mern-marketplace/server/controllers'

After I changed "Order.model" to "order.model" in order.controller.js, the compiler succeeded.

**Comment by alexzabo85** [comment]
Very good book, Thank you!

using ubuntu16 I get this error:

ERROR in ./server/controllers/order.controller.js
Module not found: Error: Can't resolve '../models/Order.model' in '/home/alex/Downloads/marketplace/server/controllers'
 @ ./server/controllers/order.controller.js 7:13-45
 @ ./server/routes/order.routes.js
 @ ./server/express.js
 @ ./server/server.js
 @ multi ./server/server.js
